### ISSUE TITLE
Liquids appear strangely over the proxy

### ISSUE THREAD

**Issue by the-blank-x** [HimbeerserverDE/mt-multiserver-proxy#126]
For some reason, water and lava (both source and flowing) are shown improperly when viewed from the proxy.

- **Minetest versions:** 5.7.0
- **Subgame:** Minetest Game
- **Proxy commit:** https://github.com/HimbeerserverDE/mt-multiserver-proxy/commit/e308d88486351b247863edcca329be61f19e8eaa
- **Plugins:** None
- **Config:**
  ```json
  {
      "Servers": {
          "localhost_30000": {
              "Addr": "localhost:30000"
          }
      },
          "NoTelnet": true,
          "DropCSMRF": true,
          "Groups": {
          "sudo": ["cmd_shutdown", "cmd_find", "cmd_addr", "cmd_alert", "cmd_send", "cmd_players", "cmd_reload", "cmd_group", "cmd_perms", "cmd_gperms", "cmd_server", "cmd_kick", "cmd_ban", "cmd_unban", "cmd_uptime", "cmd_help", "cmd_usage", "cmd_raw", "cmd_time", "cmd_timespeed"]
      },
      "UserGroups": {
          "blankie": "sudo"
      }
  }
  ```

Liquids seen on the server host:
![](https://github.com/HimbeerserverDE/mt-multiserver-proxy/assets/45762106/209d3eca-9584-403c-bd18-1ebd618be1eb)

Liquids seen from the proxy:
![](https://github.com/HimbeerserverDE/mt-multiserver-proxy/assets/45762106/772baa29-d886-4ccd-877f-688a4505cfe1)

**Comment by AFCMS** [comment]
Noticed that last time I tried (was a long time ago already)

**Comment by HimbeerserverDE** [comment]
Sorry for taking this long too respond. I'm very busy at the moment and won't be able to fix this for at least a week.

**Comment by HimbeerserverDE** [comment]
Liquid definitions in Minetest have attributes that reference its source and flowing variants using node names. The proxy makes changes to these node names to make it possible to run different sets of mods on the internal servers.

Until now the proxy didn't change these attributes because I missed them when implementing node definitions. This is now fixed in b9cff23c5da0beb1e193e705153142535d5366de, commit 8ecf41a01f54a9c3ba8bc80a5cfad31d28aaabcf makes plugins work again.

Please update the proxy and the chat command plugin and try again. It should be fixed, but please reopen the issue if it still doesn't work for you.

**Comment by the-blank-x** [comment]
I'm now getting a `Access denied. Reason: Your client sent something the server didn't expect.  Try reconnecting or updating your client.`. Here's the proxy's output:
```
2023/11/11 22:54:21 load config
2023/11/11 22:54:21 [proxy] load plugins
2023/11/11 22:54:21 [proxy] listen [::]:40000
2023/11/11 22:54:23 [[::1]:46134] -> connect
2023/11/11 22:54:24 [content server] <- deny access unexpected data
2023/11/11 22:54:24 [[::1]:46134 blankie] <-> handshake completed
2023/11/11 22:54:24 [server server] -> connect
2023/11/11 22:54:24 [server server] <- deny access unexpected data
2023/11/11 22:54:24 [server server] <-> disconnect
2023/11/11 22:54:24 [[::1]:46134 blankie] <-> disconnect
```

(also, it doesn't seem like I can reopen the issue?)

**Comment by the-blank-x** [comment]
It seems like the unexpected data message only occurs when I point the proxy to a server with a specific world. No clue why that is, but it's just a test world

**Comment by HimbeerserverDE** [comment]
I don't think this is related to the liquid issue. The Minetest server logs should have more info on why it sent the "unexpected data" error. My guess is that connecting to the game server directly messed up the authentication system, so a different username might work.
