### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by AFCMS** [HimbeerserverDE/mt-multiserver-proxy#132]
Currently you can only build and run the proxy from your main Go installation.

I am used to deploy my Minetest servers with Docker Compose which helps a lot to track regressions (with git bisect in the configuration repository which includes mods as submodules).

I would really like if there was a way to use this proxy from Docker. The biggest problem is the way to handle plugins.

**Comment by HimbeerserverDE** [comment]
I agree, Docker support should be added.

How would plugins be loaded though? A volume should work but I'm not sure if it's the best solution.

I'm going to start working on this soon but I'm not too experienced with Docker. I'll link a PR once it's ready and would be glad if you reviewed it.

**Comment by AFCMS** [comment]
I would be happy to review if you start working on Docker support.

**Comment by HimbeerserverDE** [comment]
As you can see the PR is ready and can be reviewed.

**Comment by AFCMS** [comment]
Will try to review as soon as possible, too busy rn.

**Comment by HimbeerserverDE** [comment]
I'd like to get this merged before updating to 5.8 so that it's available to 5.7 users. Do you still want to review it? If not (or if it would take a long time), would it be okay to merge the PR for now and address any problems later in a new issue?

**Comment by AFCMS** [comment]
You just reminded me of it, will try to do that today. 🙂
