### ISSUE TITLE
Add converter for MT auth backends

### ISSUE THREAD

**Issue by HimbeerserverDE** [HimbeerserverDE/mt-multiserver-proxy#65]

**Comment by BasToTheMax** [comment]
Any updates?

**Comment by HimbeerserverDE** [comment]
Added in the latest version at [cmd/mt-auth-convert](https://github.com/HimbeerserverDE/mt-multiserver-proxy/tree/main/cmd/mt-auth-convert), documentation will be added soon. Conversion from the custom backend to Minetest databases is possible too. Only supports SQLite3 at the moment, but postgres support is planned. The proxy can also load Minetest authentication databases directly now, but some features like ban will not work.
